markdown: rdiscount
paginate: 5
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, Rakefile]
permalink: pretty
highlighter: pygments
excerpt_separator: '<!-- more -->'
url: 'luysec.github.com'
baseurl: '/blog'
encoding: utf-8
only_first_p:
  show_read_more_link: true
  read_more_link_text: 'Read more'
stylus:
  compress: true
  path: ./css
values:
  is_post_index: false
gems:
  - jekyll-sitemap
